apiVersion: v1
kind: Service
metadata:
  name: book-management-service
spec:
  type: NodePort
  selector:
    app: book-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

